import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import AppHeader from "@/components/header/app-header";
import { getSession } from "@/actions/sessions";

import { SessionPayload } from "@/types/session.type";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user: SessionPayload|null = await getSession(); 
  const username: string |undefined = user?.username

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <AppHeader username={username} />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
